include:
  - project: 'devops/ci'
    ref: release/h5
    file: '/templates/.gitlab-ci-h5-spa-pro.yml'

variables:
  JLGL_CI_MODULE_NAME: 'store' # 需要改成对应的模块名,对应的访问地址是 spa.jiliguala.com/${JLGL_CI_MODULE_NAME}/index.html
  CHAT_GROUP_NAME: 'H5 DevOps' # 部署通知要发到哪个企业微信机器人
  MENTION: '["QiTengFei", "WangZhangFu"]' # 部署失败,或是发布到正式环境需要审核时要 mention 的人名列表（企业微信的  # MENTION: '["@all"]'

build:
  stage: build
  only:
    - /^deploys\/.*\/.*$/
  except:
    - branches
  script:
    - echo "building..."
    - yarn install
    - unset CI # 使得 build 过程中不 treat warning as error
    - yarn run build-${JLGL_CI_ENV}
  artifacts:
    when: on_success
    paths:
      - build/
